# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- '*'

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk'
    inputs:
      packageType: sdk
      version: 8.0.x
  
  - script: bash build.sh
    displayName: 'Build Script'


- job: Windows

  pool:
    vmImage: 'windows-latest'

  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET sdk'
    inputs:
      packageType: sdk
      version: 8.0.x
      includePreviewVersions: true # Required for preview versions
  
  - script: dotnet --info
    displayName: 'dotnet info'

  - powershell: ./build.ps1
    displayName: 'Build Script'
    env:
      Nuget__ApiKey: $(nugetApiKey)
      Nuget__SourceUrl: $(nugetSourceUrl)
