name: dotnet

on: [push]

jobs:
  # Label of the container job
  redis-integration-test:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # # Docker image that `job` executes in
    # container: mcr.microsoft.com/dotnet/sdk:5.0

    # Service containers to run with `container-job`
    # https://docs.github.com/en/free-pro-team@latest/actions/guides/creating-redis-service-containers
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis:alpine
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: build
      run: bash build.sh --target=test
